package MatrixApp;


/**
* MatrixApp/Matrix.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Matrix.idl
* Quarta-feira, 14 de Dezembro de 2016 14h48min14s GMT-03:00
*/

public interface Matrix extends MatrixOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Matrix
