package MatrixApp;


/**
* MatrixApp/MatrixPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Matrix.idl
* Quarta-feira, 14 de Dezembro de 2016 14h48min14s GMT-03:00
*/

public abstract class MatrixPOA extends org.omg.PortableServer.Servant
 implements MatrixApp.MatrixOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("mat", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MatrixApp/Matrix/mat
       {
         int a = in.read_long ();
         int b[][] = MatrixApp.MatrixPackage.MatrizHelper.read (in);
         String $result = null;
         $result = this.mat (a, b);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // MatrixApp/Matrix/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MatrixApp/Matrix:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Matrix _this() 
  {
    return MatrixHelper.narrow(
    super._this_object());
  }

  public Matrix _this(org.omg.CORBA.ORB orb) 
  {
    return MatrixHelper.narrow(
    super._this_object(orb));
  }


} // class MatrixPOA
