package MatrixApp;


/**
* MatrixApp/MatrixOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Matrix.idl
* Quarta-feira, 14 de Dezembro de 2016 16h14min02s GMT-03:00
*/

public interface MatrixOperations 
{
  String mat (int a, int[][] b);
  void shutdown ();
} // interface MatrixOperations
