package MatrixApp;

/**
* MatrixApp/MatrixHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Matrix.idl
* Quarta-feira, 14 de Dezembro de 2016 16h14min02s GMT-03:00
*/

public final class MatrixHolder implements org.omg.CORBA.portable.Streamable
{
  public MatrixApp.Matrix value = null;

  public MatrixHolder ()
  {
  }

  public MatrixHolder (MatrixApp.Matrix initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatrixApp.MatrixHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatrixApp.MatrixHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatrixApp.MatrixHelper.type ();
  }

}
